format = """
$username\
$hostname\
[ ](dimmed white)\
$directory\
$conda\
$git_branch\
$git_commit\
$git_status\
$line_break\
$character
"""
add_newline = true

[character]
success_symbol = "[❯](dimmed green)"
error_symbol = "[❯](dimmed red)"
vimcmd_symbol = "[❮](dimmed green)"
# success_symbol = "[❯](22)[❯](28)[❯](34)"
# error_symbol = "[❯](88)[❯](124)[❯](160)"

[cmd_duration]
min_time = 1000
style = "dimmed purple"
format = "[$duration]($style)"
# show_notifications = true
# min_time_to_notify = 60000

[conda]
symbol = ""
style = "dimmed green"
format = "[$symbol $environment]($style) "

[directory]
style = "dimmed white"
truncation_length = 9
truncation_symbol = ''
truncate_to_repo = true
format = '[$read_only]($read_only_style)[$path]($style) '
home_symbol = "∼"

[git_branch]
symbol = ""
style = "dimmed red"
format = "[$symbol $branch]($style) "

[git_commit]
commit_hash_length = 7
format = '[ $hash$tag]($style) '
style = 'dimmed red'
tag_disabled = false
tag_symbol = "  "

[git_status]
conflicted = '='
ahead = ' '
behind = ' '
diverged = ' '
up_to_date = ''
untracked = '[](dimmed white) '
stashed = '[](dimmed white) '
modified = '[](dimmed yellow) '
staged = '[](dimmed green) '
renamed = '[](dimmed green) '
deleted = '[](dimmed red) '
format = '[$all_status$ahead_behind]($style)'
style = "dimmed red"

[username]
format = '[$user]($style) '
show_always = false
style_root = "dimmed yellow"
style_user = "dimmed purple"

[hostname]
format = '[$ssh_symbol$hostname]($style) '
ssh_only = true
ssh_symbol = " "
style = "dimmed purple"

[line_break]
disabled = false

# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
#add_newline = true

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true
